export enum PermissionEnum {
  "PermissionScene.Save.Permission" = 2,
  "PermissionScene.Edit.Permission" = 3,
  "PermissionScene.Delete.Permission" = 4,
  "RoleScene.Save.Permission" = 6,
  "RoleScene.Edit.Permission" = 7,
  "RoleScene.Delete.Permission" = 8,
  "UserScene.Save.Permission" = 14,
  "UserScene.Edit.Permission" = 15,
  "UserScene.Delete.Permission" = 16,
  "MenuScene.Save.Permission" = 18,
  "MenuScene.Edit.Permission" = 19,
  "MenuScene.Delete.Permission" = 20,
  "ProductScene.Save.Permission" = 23,
  "ProductScene.Edit.Permission" = 24,
  "ProductScene.Delete.Permission" = 25,
  "Table.Export.Permission" = 60,
  "OrganizationScene.Save.Permission" = 62,
  "OrganizationScene.Edit.Permission" = 63,
  "OrganizationScene.Delete.Permission" = 64,
  "SupportScene.Edit.Permission" = 58,
}